version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: aitaskdb
      POSTGRES_USER: aitaskuser
      POSTGRES_PASSWORD: aitaskpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/aitaskdb
      SPRING_DATASOURCE_USERNAME: aitaskuser
      SPRING_DATASOURCE_PASSWORD: aitaskpass
    ports:
      - "8081:8081"
volumes:
  pgdata:
